# fly.toml app configuration file generated for fullstack-osa-3 on 2024-01-15T15:10:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-osa-3"
primary_region = "arn"

[build]

[env]
  PORT = "3002"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
